function prepare_block(obj,ABR)
% Daniel Stolzberg (c) 2019

% Foreground process

if isequal(obj.Timer.Running,'off')
    obj.initialize_timer;
end

Fs = ABR.DAC.SampleRate;

% write wav file to disk
audiowrite( ...
    obj.Universal.dacFile, ...
    ABR.DAC.Data,Fs, ...
    'BitsPerSample',32, ...
    'Title','ABR Stimulus')


% setup wav file reader object
obj.AFR = dsp.AudioFileReader( ...
    'Filename',ABR.DACfilename, ...
    'SamplesPerFrame',abr.Universal.frameLength, ...
    'PlayCount',1);


% setup audioplayerrecorder object
obj.APR = audioPlayerRecorder( ...
    'SampleRate',Fs, ...
    'PlayerChannelMapping',  [ABR.DACsignalCh ABR.DACtimingCh], ...
    'RecorderChannelMapping',[ABR.ADCsignalCh ABR.ADCtimingCh]);


