function prepare_block_fg(obj,ABR)
% Daniel Stolzberg (c) 2019

% write wav file to disk
audiowrite( ...
    obj.Universal.dacFile, ...
    ABR.DAC.Data,ABR.DAC.SampleRate, ...
    'BitsPerSample',32, ...
    'Title','ABR Stimulus');

obj.mapCom.Data.CommandToBg = abr.CMD.Prep;